GET http://localhost:5000/users HTTP/1.1

###
GET https://localhost:5001/users/1 HTTP/1.1

###
POST https://localhost:5001/users/2/roles HTTP/1.1
Content-Type: application/json

{
    "UserId": 2,
    "RoleId": 4
}
###
POST https://localhost:5001/users HTTP/1.1
Content-Type: application/json

{
    "Id": 0,
    "Login": "User04",
    "Name": "Ivan Sidorov",
    "Email": "ivansidorov@ivansidorov.ru",
    "Password": "0123456789"
}
###
PUT https://localhost:5001/users/2 HTTP/1.1
Content-Type: application/json

{
    "Id": 2,
    "Login": "User01",
    "Name": "Peter Petrov",
    "Email": "peter.petrov@peterpetrov.ru",
    "Password": "0123456789"
}
###
GET https://localhost:5001/roles HTTP/1.1

###
GET https://localhost:5001/roles/1 HTTP/1.1

###
POST https://localhost:5001/roles HTTP/1.1
Content-Type: application/json

{
    "Id": 0,
    "Name": "Tester"
}
###
